services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped
    depends_on:
      - nginx
    networks:
      - tunnel-network
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/mime.types:/etc/nginx/mime.types:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend-network
      - tunnel-network
  api:
    image: ghcr.io/wiratama23/tes-devops-api:latest
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    # ports:
    #   # Exposing port 8080 to the host machine
    #   - "8080:${PORT}"
    environment:
      # Pass database connection strings here so your app can read them via os.Getenv
      - DATABASE_URL=${DOCKER_DB_URL}
      - PORT=${PORT}
    depends_on:
      postgres:
       condition: service_healthy
      goose:
        condition: service_completed_successfully
    networks:
      - backend-network
      - db
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tesdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tesdb"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  goose:
    image: ghcr.io/wiratama23/tes-devops-goose:latest
    build:
      context: ./backend
      dockerfile: migrations/Dockerfile
    container_name: goose_migration
    networks:
      - db
    # This creates the live two-way portal!
    volumes:
      - ./backend/migrations:/migrations
    # Set the working directory to the folder we just mounted
    working_dir: /migrations
    # We pass the environment variables so Goose knows how to connect to Postgres
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=${DOCKER_DB_URL}
    command: up
    depends_on:
      postgres:
       condition: service_healthy

volumes:
  pgdata: {}

networks:
  db:
    driver: bridge
  backend-network:
    driver: bridge
  tunnel-network:
    driver: bridge
