name: CI/CD Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11
          working-directory: backend

  deploy:
    needs: golangci
    name: Deploy to Server
    runs-on: self-hosted 
    environment: devops

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Build and Deploy with Docker Compose
        run: |
          # --build ensures images are recreated if Go code changed
          # -d runs it in the background
          docker compose up -d --build
      
      - name: shutdown services
        if: always() # Ensure this runs even if the previous steps fail
        run: docker compose down

      - name: Cleanup old images
        run: docker image prune -f